import { BaseSeeder } from '@adonisjs/lucid/seeders'
import City from '#models/City'

export default class CitySeeder extends BaseSeeder {
  public async run() {
    await City.createMany([
      { title: 'Bogotá' },
      { title: 'Medellín' },
      { title: 'Cali' },
      { title: 'Barranquilla' },
      { title: 'Cartagena' },
      { title: 'Cúcuta' },
      { title: 'Soacha' },
      { title: 'Soledad' },
      { title: 'Bucaramanga' },
      { title: 'Bello' },
      { title: 'Villavicencio' },
      { title: 'Ibagué' },
      { title: 'Santa Marta' },
      { title: 'Valledupar' },
      { title: 'Montería' },
      { title: 'Pereira' },
      { title: 'Neiva' },
      { title: 'Pasto' },
      { title: 'Manizales' },
      { title: 'Buenaventura' },
      { title: 'Palmira' },
      { title: 'Armenia' },
      { title: 'Popayán' },
      { title: 'Sincelejo' },
      { title: 'Floridablanca' },
      { title: 'Itagüí' },
      { title: 'Tumaco' },
      { title: 'Envigado' },
      { title: 'Dosquebradas' },
      { title: 'Tuluá' },
      { title: 'Riohacha' },
      { title: 'Yopal' },
      { title: 'Girón' },
      { title: 'Magangué' },
      { title: 'Malambo' },
      { title: 'Facatativá' },
      { title: 'Chía' },
      { title: 'Jamundí' },
      { title: 'Sogamoso' },
      { title: 'Apartadó' },
      { title: 'Uribia' },
      { title: 'Girardot' },
      { title: 'Buga' },
      { title: 'Turbo' },
      { title: 'Zipaquirá' },
      { title: 'Quibdó' },
      { title: 'Fusagasugá' },
      { title: 'Ciénaga' },
      { title: 'Lorica' },
      { title: 'Rionegro' },
      { title: 'Piedecuesta' },
      { title: 'Maicao' },
      { title: 'Caldas' },
      { title: 'Chigorodó' },
      { title: 'San Andrés' },
      { title: 'Mosquera' },
      { title: 'Duitama' },
      { title: 'Cereté' },
      { title: 'La Dorada' },
      { title: 'Sabanalarga' },
      { title: 'El Carmen de Bolívar' },
      { title: 'Pitalito' },
      { title: 'Ocaña' },
      { title: 'Turbaco' },
      { title: 'Ipiales' },
      { title: 'Cajicá' },
      { title: 'Florida' },
      { title: 'Madrid' },
      { title: 'Funza' },
      { title: 'Sahagún' },
      { title: 'Aguachica' },
      { title: 'Chía' },
      { title: 'La Estrella' },
      { title: 'Sabaneta' },
      { title: 'El Banco' },
      { title: 'Yumbo' },
      { title: 'Caucasia' },
      { title: 'Montelíbano' },
      { title: 'Planeta Rica' },
      { title: 'Tierralta' },
      { title: 'Puerto Asís' },
      { title: 'San Vicente del Caguán' },
      { title: 'Garzón' },
      { title: 'El Bagre' },
      { title: 'Aguazul' },
      { title: 'La Ceja' },
      { title: 'Sonsón' },
      { title: 'Tame' },
      { title: 'Pamplona' },
      { title: 'Sabanagrande' },
      { title: 'San Gil' },
      { title: 'El Espinal' },
      { title: 'Puerto Tejada' },
      { title: 'Coveñas' },
      { title: 'Guamal' },
      { title: 'San José del Guaviare' },
      { title: 'Leticia' },
      { title: 'Mocoa' },
      { title: 'Mitú' },
      { title: 'Inírida' }
    ])
  }
}
