import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Project from '#models/Project'

export default class ProjectSeeder extends BaseSeeder {
    public async run() {
        await Project.createMany([
            {
                title: 'Project A',
                description: 'Description of Project A',
                userId: 1,
                statusId: 1,
                clientId: 2,
                startDate: new Date('2025-05-01'),
                endDate: new Date('2025-12-31'),
            },
            {
                title: 'Project B',
                description: 'Description of Project B',
                userId: 2,
                statusId: 2,
                clientId: 1,
                startDate: new Date('2025-06-01'),
                endDate: new Date('2025-11-30'),
            },
            {
        title: 'Project Beta',
        description: 'Beta project for new client',
        userId: 2,
        statusId: 6,
        clientId: 3,
        startDate: new Date('2025-02-01'),
        endDate: new Date('2025-07-15'),
      },
      {
        title: 'Project Gamma',
        description: 'Gamma project with advanced features',
        userId: 3,
        statusId: 7,
        clientId: 4,
        startDate: new Date('2025-03-05'),
        endDate: new Date('2025-08-20'),
      },
      {
        title: 'Project Delta',
        description: 'Delta project for internal use',
        userId: 4,
        statusId: 8,
        clientId: 5,
        startDate: new Date('2025-04-10'),
        endDate: new Date('2025-09-25'),
      },
      {
        title: 'Project Epsilon',
        description: 'Epsilon project for testing',
        userId: 5,
        statusId: 9,
        clientId: 6,
        startDate: new Date('2025-05-15'),
        endDate: new Date('2025-10-30'),
      },
      {
        title: 'Project Zeta',
        description: 'Zeta project for automation',
        userId: 6,
        statusId: 5,
        clientId: 7,
        startDate: new Date('2025-06-20'),
        endDate: new Date('2025-11-15'),
      },
      {
        title: 'Project Eta',
        description: 'Eta project for mobile development',
        userId: 7,
        statusId: 6,
        clientId: 8,
        startDate: new Date('2025-07-25'),
        endDate: new Date('2025-12-20'),
      },
      {
        title: 'Project Theta',
        description: 'Theta project for web platform',
        userId: 8,
        statusId: 7,
        clientId: 9,
        startDate: new Date('2025-08-30'),
        endDate: new Date('2026-01-25'),
      },
      {
        title: 'Project Iota',
        description: 'Iota project for analytics',
        userId: 9,
        statusId: 8,
        clientId: 10,
        startDate: new Date('2025-09-05'),
        endDate: new Date('2026-02-28'),
      },
      {
        title: 'Project Kappa',
        description: 'Kappa project for integration',
        userId: 10,
        statusId: 9,
        clientId: 11,
        startDate: new Date('2025-10-10'),
        endDate: new Date('2026-03-15'),
      },
      {
        title: 'Project Lambda',
        description: 'Lambda project for migration',
        userId: 11,
        statusId: 5,
        clientId: 12,
        startDate: new Date('2025-11-15'),
        endDate: new Date('2026-04-20'),
      },
      {
        title: 'Project Mu',
        description: 'Mu project for cloud services',
        userId: 12,
        statusId: 6,
        clientId: 13,
        startDate: new Date('2025-12-20'),
        endDate: new Date('2026-05-25'),
      },
      {
        title: 'Project Nu',
        description: 'Nu project for security',
        userId: 13,
        statusId: 7,
        clientId: 14,
        startDate: new Date('2026-01-25'),
        endDate: new Date('2026-06-30'),
      },
      {
        title: 'Project Xi',
        description: 'Xi project for performance',
        userId: 14,
        statusId: 8,
        clientId: 15,
        startDate: new Date('2026-02-28'),
        endDate: new Date('2026-07-15'),
      },
      {
        title: 'Project Omicron',
        description: 'Omicron project for scalability',
        userId: 15,
        statusId: 9,
        clientId: 16,
        startDate: new Date('2026-03-05'),
        endDate: new Date('2026-08-20'),
      },
      {
        title: 'Project Pi',
        description: 'Pi project for AI integration',
        userId: 16,
        statusId: 5,
        clientId: 17,
        startDate: new Date('2026-04-10'),
        endDate: new Date('2026-09-25'),
      },
      {
        title: 'Project Rho',
        description: 'Rho project for IoT',
        userId: 17,
        statusId: 6,
        clientId: 18,
        startDate: new Date('2026-05-15'),
        endDate: new Date('2026-10-30'),
      },
      {
        title: 'Project Sigma',
        description: 'Sigma project for DevOps',
        userId: 18,
        statusId: 7,
        clientId: 19,
        startDate: new Date('2026-06-20'),
        endDate: new Date('2026-11-15'),
      },
      {
        title: 'Project Tau',
        description: 'Tau project for automation',
        userId: 19,
        statusId: 8,
        clientId: 20,
        startDate: new Date('2026-07-25'),
        endDate: new Date('2026-12-20'),
      },
      {
        title: 'Project Upsilon',
        description: 'Upsilon project for reporting',
        userId: 20,
        statusId: 9,
        clientId: 21,
        startDate: new Date('2026-08-30'),
        endDate: new Date('2027-01-25'),
      },
      {
        title: 'Project Phi',
        description: 'Phi project for dashboards',
        userId: 21,
        statusId: 5,
        clientId: 22,
        startDate: new Date('2026-09-05'),
        endDate: new Date('2027-02-28'),
      },
      {
        title: 'Project Chi',
        description: 'Chi project for notifications',
        userId: 22,
        statusId: 6,
        clientId: 23,
        startDate: new Date('2026-10-10'),
        endDate: new Date('2027-03-15'),
      },
      {
        title: 'Project Psi',
        description: 'Psi project for user management',
        userId: 23,
        statusId: 7,
        clientId: 24,
        startDate: new Date('2026-11-15'),
        endDate: new Date('2027-04-20'),
      },
      {
        title: 'Project Omega',
        description: 'Omega project for final delivery',
        userId: 24,
        statusId: 8,
        clientId: 25,
        startDate: new Date('2026-12-20'),
        endDate: new Date('2027-05-25'),
      },
      {
        title: 'Project Nova',
        description: 'Nova project for innovation',
        userId: 25,
        statusId: 9,
        clientId: 1,
        startDate: new Date('2027-01-25'),
        endDate: new Date('2027-06-30'),
      },
        ])
    }
}
