import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Task from '#models/Task'

export default class TaskSeeder extends BaseSeeder {
  public async run() {
    await Task.createMany([
      {
        title: 'Task 1',
        description: 'Initial analysis',
        projectId: 1,
        userId: 1,
        priorityId: 1,
        statusId: 1,
        dueDate: new Date('2025-02-15'),
      },
      {
        title: 'Task 2',
        description: 'Requirement gathering',
        projectId: 2,
        userId: 2,
        priorityId: 2,
        statusId: 2,
        dueDate: new Date('2025-03-10'),
      },
      {
        title: 'Task 3',
        description: 'Design database schema',
        projectId: 3,
        userId: 3,
        priorityId: 3,
        statusId: 3,
        dueDate: new Date('2025-04-05'),
      },
      {
        title: 'Task 4',
        description: 'Develop API endpoints',
        projectId: 4,
        userId: 4,
        priorityId: 1,
        statusId: 4,
        dueDate: new Date('2025-05-01'),
      },
      {
        title: 'Task 5',
        description: 'Frontend implementation',
        projectId: 5,
        userId: 5,
        priorityId: 2,
        statusId: 1,
        dueDate: new Date('2025-06-10'),
      },
      {
        title: 'Task 6',
        description: 'Testing phase 1',
        projectId: 6,
        userId: 6,
        priorityId: 3,
        statusId: 2,
        dueDate: new Date('2025-07-15'),
      },
      {
        title: 'Task 7',
        description: 'Bug fixing',
        projectId: 7,
        userId: 7,
        priorityId: 1,
        statusId: 3,
        dueDate: new Date('2025-08-20'),
      },
      {
        title: 'Task 8',
        description: 'Deploy to staging',
        projectId: 8,
        userId: 8,
        priorityId: 2,
        statusId: 4,
        dueDate: new Date('2025-09-25'),
      },
      {
        title: 'Task 9',
        description: 'Client feedback',
        projectId: 9,
        userId: 9,
        priorityId: 3,
        statusId: 1,
        dueDate: new Date('2025-10-30'),
      },
      {
        title: 'Task 10',
        description: 'Documentation',
        projectId: 10,
        userId: 10,
        priorityId: 1,
        statusId: 2,
        dueDate: new Date('2025-11-15'),
      },
      {
        title: 'Task 11',
        description: 'Training session',
        projectId: 11,
        userId: 11,
        priorityId: 2,
        statusId: 3,
        dueDate: new Date('2025-12-20'),
      },
      {
        title: 'Task 12',
        description: 'Release v1.0',
        projectId: 12,
        userId: 12,
        priorityId: 3,
        statusId: 4,
        dueDate: new Date('2026-01-25'),
      },
      {
        title: 'Task 13',
        description: 'Post-release support',
        projectId: 13,
        userId: 13,
        priorityId: 1,
        statusId: 1,
        dueDate: new Date('2026-02-28'),
      },
      {
        title: 'Task 14',
        description: 'Performance optimization',
        projectId: 14,
        userId: 14,
        priorityId: 2,
        statusId: 2,
        dueDate: new Date('2026-03-15'),
      },
      {
        title: 'Task 15',
        description: 'Security audit',
        projectId: 15,
        userId: 15,
        priorityId: 3,
        statusId: 3,
        dueDate: new Date('2026-04-20'),
      },
      {
        title: 'Task 16',
        description: 'Integrate third-party API',
        projectId: 16,
        userId: 16,
        priorityId: 1,
        statusId: 4,
        dueDate: new Date('2026-05-25'),
      },
      {
        title: 'Task 17',
        description: 'Mobile app development',
        projectId: 17,
        userId: 17,
        priorityId: 2,
        statusId: 1,
        dueDate: new Date('2026-06-30'),
      },
      {
        title: 'Task 18',
        description: 'UI/UX improvements',
        projectId: 18,
        userId: 18,
        priorityId: 3,
        statusId: 2,
        dueDate: new Date('2026-07-15'),
      },
      {
        title: 'Task 19',
        description: 'Automated testing',
        projectId: 19,
        userId: 19,
        priorityId: 1,
        statusId: 3,
        dueDate: new Date('2026-08-20'),
      },
      {
        title: 'Task 20',
        description: 'Continuous integration setup',
        projectId: 20,
        userId: 20,
        priorityId: 2,
        statusId: 4,
        dueDate: new Date('2026-09-25'),
      },
      {
        title: 'Task 21',
        description: 'Monitoring and alerts',
        projectId: 21,
        userId: 21,
        priorityId: 3,
        statusId: 1,
        dueDate: new Date('2026-10-30'),
      },
      {
        title: 'Task 22',
        description: 'Customer onboarding',
        projectId: 22,
        userId: 22,
        priorityId: 1,
        statusId: 2,
        dueDate: new Date('2026-11-15'),
      },
      {
        title: 'Task 23',
        description: 'Feature planning',
        projectId: 23,
        userId: 23,
        priorityId: 2,
        statusId: 3,
        dueDate: new Date('2026-12-20'),
      },
      {
        title: 'Task 24',
        description: 'Retrospective meeting',
        projectId: 24,
        userId: 24,
        priorityId: 3,
        statusId: 4,
        dueDate: new Date('2027-01-25'),
      },
      {
        title: 'Task 25',
        description: 'Project closure',
        projectId: 25,
        userId: 25,
        priorityId: 1,
        statusId: 1,
        dueDate: new Date('2027-02-28'),
      },
    ])
  }
}
