import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Task from '#models/Task'

export default class TaskSeeder extends BaseSeeder {
  public async run() {
    await Task.createMany([
      {
  title: 'Tarea 1',
  description: 'Análisis inicial',
  projectId: 1,
  userId: 1,
  priorityId: 1,
  statusId: 1,
  dueDate: new Date('2025-02-15'),
},
{
  title: 'Tarea 2',
  description: 'Recolección de requerimientos',
  projectId: 2,
  userId: 2,
  priorityId: 2,
  statusId: 2,
  dueDate: new Date('2025-03-10'),
},
{
  title: 'Tarea 3',
  description: 'Diseñar el esquema de base de datos',
  projectId: 3,
  userId: 3,
  priorityId: 3,
  statusId: 3,
  dueDate: new Date('2025-04-05'),
},
{
  title: 'Tarea 4',
  description: 'Desarrollar endpoints de API',
  projectId: 4,
  userId: 4,
  priorityId: 1,
  statusId: 4,
  dueDate: new Date('2025-05-01'),
},
{
  title: 'Tarea 5',
  description: 'Implementación del frontend',
  projectId: 5,
  userId: 5,
  priorityId: 2,
  statusId: 1,
  dueDate: new Date('2025-06-10'),
},
{
  title: 'Tarea 6',
  description: 'Primera fase de pruebas',
  projectId: 6,
  userId: 6,
  priorityId: 3,
  statusId: 2,
  dueDate: new Date('2025-07-15'),
},
{
  title: 'Tarea 7',
  description: 'Corrección de errores',
  projectId: 7,
  userId: 7,
  priorityId: 1,
  statusId: 3,
  dueDate: new Date('2025-08-20'),
},
{
  title: 'Tarea 8',
  description: 'Despliegue a staging',
  projectId: 8,
  userId: 8,
  priorityId: 2,
  statusId: 4,
  dueDate: new Date('2025-09-25'),
},
{
  title: 'Tarea 9',
  description: 'Retroalimentación del cliente',
  projectId: 9,
  userId: 9,
  priorityId: 3,
  statusId: 1,
  dueDate: new Date('2025-10-30'),
},
{
  title: 'Tarea 10',
  description: 'Documentación',
  projectId: 10,
  userId: 10,
  priorityId: 1,
  statusId: 2,
  dueDate: new Date('2025-11-15'),
},
{
  title: 'Tarea 11',
  description: 'Sesión de capacitación',
  projectId: 11,
  userId: 11,
  priorityId: 2,
  statusId: 3,
  dueDate: new Date('2025-12-20'),
},
{
  title: 'Tarea 12',
  description: 'Lanzamiento v1.0',
  projectId: 12,
  userId: 12,
  priorityId: 3,
  statusId: 4,
  dueDate: new Date('2026-01-25'),
},
{
  title: 'Tarea 13',
  description: 'Soporte post-lanzamiento',
  projectId: 13,
  userId: 13,
  priorityId: 1,
  statusId: 1,
  dueDate: new Date('2026-02-28'),
},
{
  title: 'Tarea 14',
  description: 'Optimización de rendimiento',
  projectId: 14,
  userId: 14,
  priorityId: 2,
  statusId: 2,
  dueDate: new Date('2026-03-15'),
},
{
  title: 'Tarea 15',
  description: 'Auditoría de seguridad',
  projectId: 15,
  userId: 15,
  priorityId: 3,
  statusId: 3,
  dueDate: new Date('2026-04-20'),
},
{
  title: 'Tarea 16',
  description: 'Integrar API de terceros',
  projectId: 16,
  userId: 16,
  priorityId: 1,
  statusId: 4,
  dueDate: new Date('2026-05-25'),
},
{
  title: 'Tarea 17',
  description: 'Desarrollo de aplicación móvil',
  projectId: 17,
  userId: 17,
  priorityId: 2,
  statusId: 1,
  dueDate: new Date('2026-06-30'),
},
{
  title: 'Tarea 18',
  description: 'Mejoras de UI/UX',
  projectId: 18,
  userId: 18,
  priorityId: 3,
  statusId: 2,
  dueDate: new Date('2026-07-15'),
},
{
  title: 'Tarea 19',
  description: 'Pruebas automatizadas',
  projectId: 19,
  userId: 19,
  priorityId: 1,
  statusId: 3,
  dueDate: new Date('2026-08-20'),
},
{
  title: 'Tarea 20',
  description: 'Configuración de integración continua',
  projectId: 20,
  userId: 20,
  priorityId: 2,
  statusId: 4,
  dueDate: new Date('2026-09-25'),
},
{
  title: 'Tarea 21',
  description: 'Monitoreo y alertas',
  projectId: 21,
  userId: 21,
  priorityId: 3,
  statusId: 1,
  dueDate: new Date('2026-10-30'),
},
{
  title: 'Tarea 22',
  description: 'Incorporación de clientes',
  projectId: 22,
  userId: 22,
  priorityId: 1,
  statusId: 2,
  dueDate: new Date('2026-11-15'),
},
{
  title: 'Tarea 23',
  description: 'Planificación de funcionalidades',
  projectId: 23,
  userId: 23,
  priorityId: 2,
  statusId: 3,
  dueDate: new Date('2026-12-20'),
},
{
  title: 'Tarea 24',
  description: 'Reunión de retrospectiva',
  projectId: 24,
  userId: 24,
  priorityId: 3,
  statusId: 4,
  dueDate: new Date('2027-01-25'),
},
{
  title: 'Tarea 25',
  description: 'Cierre de proyecto',
  projectId: 25,
  userId: 25,
  priorityId: 1,
  statusId: 1,
  dueDate: new Date('2027-02-28'),
}

    ])
  }
}
