import { BaseSeeder } from '@adonisjs/lucid/seeders'
import User from '#models/User'

export default class UserSeeder extends BaseSeeder {
  public async run() {
    await User.createMany([
      {
        typeDocumentId: 1,
        document: 1234567890,
        firstName: 'Juan',
        lastName: 'Pérez',
        email: 'admin@mail.com',
        password: '123456789',
        telephone: 3001234567,
        cityId: 1
      },
      {
        typeDocumentId: 2,
        document: 9876543210,
        firstName: 'Ana',
        lastName: 'Gómez',
        email: 'ana.gomez@example.com',
        password: 'password456',
        telephone: 3007654321,
        cityId: 2,
      },
      {
        typeDocumentId: 3,
        document: 1122334455,
        firstName: 'Carlos',
        lastName: 'Ramírez',
        email: 'carlos.ramirez@example.com',
        password: 'password789',
        telephone: 3101234567,
        cityId: 3,
      },
      {
        typeDocumentId: 4,
        document: 5566778899,
        firstName: 'María',
        lastName: 'Fernández',
        email: 'maria.fernandez@example.com',
        password: 'password321',
        telephone: 3209876543,
        cityId: 4,
      },
      {
        typeDocumentId: 5,
        document: 9988776655,
        firstName: 'Luis',
        lastName: 'Martínez',
        email: 'luis.martinez@example.com',
        password: 'password654',
        telephone: 3156789123,
        cityId: 5,
      },
      {
        typeDocumentId: 6,
        document: 2233445566,
        firstName: 'Laura',
        lastName: 'Suárez',
        email: 'laura.suarez@example.com',
        password: 'password987',
        telephone: 3123456789,
        cityId: 6,
      },
      {
        typeDocumentId: 7,
        document: 3344556677,
        firstName: 'Pedro',
        lastName: 'Moreno',
        email: 'pedro.moreno@example.com',
        password: 'password741',
        telephone: 3134567890,
        cityId: 7,
      },
      {
        typeDocumentId: 8,
        document: 4455667788,
        firstName: 'Sofía',
        lastName: 'Castro',
        email: 'sofia.castro@example.com',
        password: 'password852',
        telephone: 3145678901,
        cityId: 8,
      },
      {
        typeDocumentId: 1,
        document: 5566778890,
        firstName: 'Miguel',
        lastName: 'Jiménez',
        email: 'miguel.jimenez@example.com',
        password: 'password963',
        telephone: 3156789012,
        cityId: 9,
      },
      {
        typeDocumentId: 2,
        document: 6677889900,
        firstName: 'Valentina',
        lastName: 'López',
        email: 'valentina.lopez@example.com',
        password: 'password159',
        telephone: 3167890123,
        cityId: 10,
      },
      {
        typeDocumentId: 3,
        document: 7788990011,
        firstName: 'Andrés',
        lastName: 'Torres',
        email: 'andres.torres@example.com',
        password: 'password357',
        telephone: 3178901234,
        cityId: 11,
      },
      {
        typeDocumentId: 4,
        document: 8899001122,
        firstName: 'Camila',
        lastName: 'Rojas',
        email: 'camila.rojas@example.com',
        password: 'password258',
        telephone: 3189012345,
        cityId: 12,
      },
      {
        typeDocumentId: 5,
        document: 9900112233,
        firstName: 'Jorge',
        lastName: 'Vargas',
        email: 'jorge.vargas@example.com',
        password: 'password456',
        telephone: 3190123456,
        cityId: 13,
      },
      {
        typeDocumentId: 6,
        document: 1011121314,
        firstName: 'Natalia',
        lastName: 'Mendoza',
        email: 'natalia.mendoza@example.com',
        password: 'password654',
        telephone: 3201234567,
        cityId: 14,
      },
      {
        typeDocumentId: 7,
        document: 1213141516,
        firstName: 'Felipe',
        lastName: 'Cárdenas',
        email: 'felipe.cardenas@example.com',
        password: 'password789',
        telephone: 3212345678,
        cityId: 15,
      },
      {
        typeDocumentId: 8,
        document: 1314151617,
        firstName: 'Daniela',
        lastName: 'García',
        email: 'daniela.garcia@example.com',
        password: 'password321',
        telephone: 3223456789,
        cityId: 16,
      },
      {
        typeDocumentId: 1,
        document: 1415161718,
        firstName: 'Esteban',
        lastName: 'Ruiz',
        email: 'esteban.ruiz@example.com',
        password: 'password987',
        telephone: 3234567890,
        cityId: 17,
      },
      {
        typeDocumentId: 2,
        document: 1516171819,
        firstName: 'Paula',
        lastName: 'Santos',
        email: 'paula.santos@example.com',
        password: 'password123',
        telephone: 3245678901,
        cityId: 18,
      },
      {
        typeDocumentId: 3,
        document: 1617181920,
        firstName: 'Ricardo',
        lastName: 'Ortega',
        email: 'ricardo.ortega@example.com',
        password: 'password456',
        telephone: 3256789012,
        cityId: 19,
      },
      {
        typeDocumentId: 4,
        document: 1718192021,
        firstName: 'Juliana',
        lastName: 'Salazar',
        email: 'juliana.salazar@example.com',
        password: 'password789',
        telephone: 3267890123,
        cityId: 20,
      },
      {
        typeDocumentId: 5,
        document: 1819202122,
        firstName: 'Gabriela',
        lastName: 'Mejía',
        email: 'gabriela.mejia@example.com',
        password: 'password111',
        telephone: 3278901234,
        cityId: 21,
      },
      {
        typeDocumentId: 6,
        document: 1920212223,
        firstName: 'Sebastián',
        lastName: 'Navarro',
        email: 'sebastian.navarro@example.com',
        password: 'password222',
        telephone: 3289012345,
        cityId: 22,
      },
      {
        typeDocumentId: 7,
        document: 2021222324,
        firstName: 'Lucía',
        lastName: 'Pineda',
        email: 'lucia.pineda@example.com',
        password: 'password333',
        telephone: 3290123456,
        cityId: 23,
      },
      {
        typeDocumentId: 8,
        document: 2122232425,
        firstName: 'Tomás',
        lastName: 'Silva',
        email: 'tomas.silva@example.com',
        password: 'password444',
        telephone: 3301234567,
        cityId: 24,
      },
      {
        typeDocumentId: 1,
        document: 2223242526,
        firstName: 'Isabella',
        lastName: 'Cruz',
        email: 'isabella.cruz@example.com',
        password: 'password555',
        telephone: 3312345678,
        cityId: 25,
      },
      {
        typeDocumentId: 2,
        document: 2324252627,
        firstName: 'Mateo',
        lastName: 'Vera',
        email: 'mateo.vera@example.com',
        password: 'password666',
        telephone: 3323456789,
        cityId: 26,
      },
      {
        typeDocumentId: 3,
        document: 2425262728,
        firstName: 'Martina',
        lastName: 'Herrera',
        email: 'martina.herrera@example.com',
        password: 'password777',
        telephone: 3334567890,
        cityId: 27,
      },
      {
        typeDocumentId: 4,
        document: 2526272829,
        firstName: 'Samuel',
        lastName: 'Peña',
        email: 'samuel.pena@example.com',
        password: 'password888',
        telephone: 3345678901,
        cityId: 28,
      },
      {
        typeDocumentId: 5,
        document: 2627282930,
        firstName: 'Victoria',
        lastName: 'Mora',
        email: 'victoria.mora@example.com',
        password: 'password999',
        telephone: 3356789012,
        cityId: 28,
      },
      {
        typeDocumentId: 6,
        document: 2728293031,
        firstName: 'Emilio',
        lastName: 'Guerrero',
        email: 'emilio.guerrero@example.com',
        password: 'password000',
        telephone: 3367890123,
        cityId: 28,
      }
    ])
  }
}
