import { BaseSeeder } from '@adonisjs/lucid/seeders'
import User from '#models/User'

export default class UserSeeder extends BaseSeeder {
  public async run() {
    await User.createMany([
      {
        typeDocumentId: 1,
        document: 1234567890,
        firstName: 'Juan',
        lastName: 'Pérez',
        email: 'juan.perez@example.com',
        password: 'password123',
        telephone: 3001234567,
        cityId: 1,
      },
      {
        typeDocumentId: 2,
        document: 9876543210,
        firstName: 'Ana',
        lastName: 'Gómez',
        email: 'ana.gomez@example.com',
        password: 'password456',
        telephone: 3007654321,
        cityId: 2,
      },
      {
        typeDocumentId: 2,
        document: 1000000002,
        firstName: 'Anatulia',
        lastName: 'Guzman',
        email: 'anatulia.guzman@example.com',
        password: 'password45p',
        telephone: 3115896969,
        cityId: 2,
      },
      {
        typeDocumentId: 3,
        document: 1000000003,
        firstName: 'Carlos',
        lastName: 'Ramírez',
        email: 'carlos.ramirez@example.com',
        password: 'password789',
        telephone: 3001000003,
        cityId: 3,
      },
      {
        typeDocumentId: 4,
        document: 1000000004,
        firstName: 'Luisa',
        lastName: 'Martínez',
        email: 'luisa.martinez@example.com',
        password: 'password101',
        telephone: 3001000004,
        cityId: 4,
      },
      {
        typeDocumentId: 5,
        document: 1000000005,
        firstName: 'Pedro',
        lastName: 'García',
        email: 'pedro.garcia@example.com',
        password: 'password102',
        telephone: 3001000005,
        cityId: 5,
      },
      {
        typeDocumentId: 6,
        document: 1000000006,
        firstName: 'María',
        lastName: 'López',
        email: 'maria.lopez@example.com',
        password: 'password103',
        telephone: 3001000006,
        cityId: 6,
      },
      {
        typeDocumentId: 7,
        document: 1000000007,
        firstName: 'Jorge',
        lastName: 'Torres',
        email: 'jorge.torres@example.com',
        password: 'password104',
        telephone: 3001000007,
        cityId: 7,
      },
      {
        typeDocumentId: 8,
        document: 1000000008,
        firstName: 'Paula',
        lastName: 'Moreno',
        email: 'paula.moreno@example.com',
        password: 'password105',
        telephone: 3001000008,
        cityId: 8,
      },
      {
        typeDocumentId: 1,
        document: 1000000009,
        firstName: 'Andrés',
        lastName: 'Jiménez',
        email: 'andres.jimenez@example.com',
        password: 'password106',
        telephone: 3001000009,
        cityId: 9,
      },
      {
        typeDocumentId: 2,
        document: 1000000010,
        firstName: 'Diana',
        lastName: 'Ruiz',
        email: 'diana.ruiz@example.com',
        password: 'password107',
        telephone: 3001000010,
        cityId: 10,
      },
      {
        typeDocumentId: 3,
        document: 1000000011,
        firstName: 'Felipe',
        lastName: 'Castro',
        email: 'felipe.castro@example.com',
        password: 'password108',
        telephone: 3001000011,
        cityId: 11,
      },
      {
        typeDocumentId: 4,
        document: 1000000012,
        firstName: 'Camila',
        lastName: 'Vargas',
        email: 'camila.vargas@example.com',
        password: 'password109',
        telephone: 3001000012,
        cityId: 12,
      },
      {
        typeDocumentId: 5,
        document: 1000000013,
        firstName: 'Ricardo',
        lastName: 'Sánchez',
        email: 'ricardo.sanchez@example.com',
        password: 'password110',
        telephone: 3001000013,
        cityId: 13,
      },
      {
        typeDocumentId: 6,
        document: 1000000014,
        firstName: 'Laura',
        lastName: 'Mendoza',
        email: 'laura.mendoza@example.com',
        password: 'password111',
        telephone: 3001000014,
        cityId: 14,
      },
      {
        typeDocumentId: 7,
        document: 1000000015,
        firstName: 'Santiago',
        lastName: 'Cruz',
        email: 'santiago.cruz@example.com',
        password: 'password112',
        telephone: 3001000015,
        cityId: 15,
      },
      {
        typeDocumentId: 8,
        document: 1000000016,
        firstName: 'Valentina',
        lastName: 'Herrera',
        email: 'valentina.herrera@example.com',
        password: 'password113',
        telephone: 3001000016,
        cityId: 16,
      },
      {
        typeDocumentId: 1,
        document: 1000000017,
        firstName: 'Sebastián',
        lastName: 'Rojas',
        email: 'sebastian.rojas@example.com',
        password: 'password114',
        telephone: 3001000017,
        cityId: 17,
      },
      {
        typeDocumentId: 2,
        document: 1000000018,
        firstName: 'Natalia',
        lastName: 'Silva',
        email: 'natalia.silva@example.com',
        password: 'password115',
        telephone: 3001000018,
        cityId: 18,
      },
      {
        typeDocumentId: 3,
        document: 1000000019,
        firstName: 'Miguel',
        lastName: 'Ortega',
        email: 'miguel.ortega@example.com',
        password: 'password116',
        telephone: 3001000019,
        cityId: 19,
      },
      {
        typeDocumentId: 4,
        document: 1000000020,
        firstName: 'Juliana',
        lastName: 'Guerrero',
        email: 'juliana.guerrero@example.com',
        password: 'password117',
        telephone: 3001000020,
        cityId: 20,
      },
      {
        typeDocumentId: 5,
        document: 1000000021,
        firstName: 'Oscar',
        lastName: 'Peña',
        email: 'oscar.pena@example.com',
        password: 'password118',
        telephone: 3001000021,
        cityId: 21,
      },
      {
        typeDocumentId: 6,
        document: 1000000022,
        firstName: 'Andrea',
        lastName: 'Salazar',
        email: 'andrea.salazar@example.com',
        password: 'password119',
        telephone: 3001000022,
        cityId: 22,
      },
      {
        typeDocumentId: 7,
        document: 1000000023,
        firstName: 'Mauricio',
        lastName: 'Vega',
        email: 'mauricio.vega@example.com',
        password: 'password120',
        telephone: 3001000023,
        cityId: 23,
      },
      {
        typeDocumentId: 8,
        document: 1000000024,
        firstName: 'Tatiana',
        lastName: 'Córdoba',
        email: 'tatiana.cordoba@example.com',
        password: 'password121',
        telephone: 3001000024,
        cityId: 24,
      },
      {
        typeDocumentId: 1,
        document: 1000000025,
        firstName: 'Esteban',
        lastName: 'Pineda',
        email: 'esteban.pineda@example.com',
        password: 'password122',
        telephone: 3001000025,
        cityId: 25,
      },
      {
        typeDocumentId: 2,
        document: 1000000026,
        firstName: 'Lorena',
        lastName: 'Mejía',
        email: 'lorena.mejia@example.com',
        password: 'password123',
        telephone: 3001000026,
        cityId: 26,
      },
      {
        typeDocumentId: 3,
        document: 1000000027,
        firstName: 'David',
        lastName: 'Navarro',
        email: 'david.navarro@example.com',
        password: 'password124',
        telephone: 3001000027,
        cityId: 27,
      },
      {
        typeDocumentId: 4,
        document: 1000000028,
        firstName: 'Gabriela',
        lastName: 'Mora',
        email: 'gabriela.mora@example.com',
        password: 'password125',
        telephone: 3001000028,
        cityId: 28,
      },
      {
        typeDocumentId: 5,
        document: 1000000029,
        firstName: 'Alejandro',
        lastName: 'Reyes',
        email: 'alejandro.reyes@example.com',
        password: 'password126',
        telephone: 3001000029,
        cityId: 29,
      },
      {
        typeDocumentId: 6,
        document: 1000000030,
        firstName: 'Isabel',
        lastName: 'Castaño',
        email: 'isabel.castano@example.com',
        password: 'password127',
        telephone: 3001000030,
        cityId: 30,
      },
    ])
  }
}
